# Generated by Django 5.2.4 on 2025-08-04 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En Proceso'), ('ESCALADO', 'Escalado a Técnico'), ('RESUELTO_BOT', 'Resuelto por Bot'), ('RESUELTO_TECNICO', 'Resuelto por Técnico'), ('CERRADO', 'Cerrado')], default='NUEVO', max_length=20, verbose_name='Estado del Ticket')),
                ('canal_origen', models.CharField(choices=[('WEB', 'Web'), ('TELEGRAM', 'Telegram')], default='WEB', max_length=10, verbose_name='Canal de Origen')),
                ('descripcion_inicial', models.TextField(blank=True, null=True, verbose_name='Descripción Inicial del Usuario')),
                ('descripcion_confirmada_ia', models.TextField(blank=True, null=True, verbose_name='Resumen de la IA')),
                ('calificacion', models.IntegerField(blank=True, choices=[(1, 'Mala'), (2, 'Regular'), (3, 'Buena'), (4, 'Muy Buena'), (5, 'Excelente')], null=True, verbose_name='Calificación del Usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LogInteraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Contenido del Mensaje')),
                ('emisor', models.CharField(choices=[('SISTEMA', 'Sistema'), ('USUARIO', 'Usuario')], max_length=10, verbose_name='Emisor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tickets.ticket', verbose_name='Ticket Asociado')),
            ],
            options={
                'verbose_name': 'Log de Interacción',
                'verbose_name_plural': 'Logs de Interacciones',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
