# Generated by Django 5.2.4 on 2025-08-04 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='El ID único del chat de Telegram para enviarle notificaciones.', max_length=100, null=True, unique=True, verbose_name='ID de Chat de Telegram')),
                ('is_active_technician', models.BooleanField(default=True, help_text='Desmarcar para que este técnico no reciba nuevas notificaciones de tickets.', verbose_name='Técnico Activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Técnico',
                'verbose_name_plural': 'Perfiles de Técnicos',
            },
        ),
    ]
