# Generated by Django 5.2.4 on 2025-08-04 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_technicianprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(upload_to='knowledge_base/', verbose_name='Archivo')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('estado_procesamiento', models.CharField(choices=[('PENDING', 'Pendiente de Procesamiento'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Procesado Exitosamente'), ('FAILED', 'Falló el Procesamiento')], default='PENDING', max_length=20, verbose_name='Estado de Procesamiento')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('ultimo_error', models.TextField(blank=True, null=True, verbose_name='Último Error')),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cargados', to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
            ],
            options={
                'verbose_name': 'Documento de Conocimiento',
                'verbose_name_plural': 'Documentos de Conocimiento',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
