# Generated by Django 5.2.4 on 2025-08-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_knowledgedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingTelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(max_length=100, verbose_name='ID de Chat de Telegram de Destino')),
                ('message_text', models.TextField(verbose_name='Contenido del Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Mensaje Saliente de Telegram',
                'verbose_name_plural': 'Mensajes Salientes de Telegram',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
