# Generated by Django 5.2.4 on 2025-08-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_outgoingtelegrammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='tipo_documento',
            field=models.CharField(choices=[('CONOCIMIENTO_GENERAL', 'Conocimiento General'), ('MANUAL_TECNICO', 'Manual Técnico')], default='CONOCIMIENTO_GENERAL', max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tema Principal / Subtema'),
        ),
        migrations.AlterField(
            model_name='loginteraccion',
            name='emisor',
            field=models.CharField(choices=[('SISTEMA', 'Sistema'), ('USUARIO', 'Usuario'), ('TECNICO', 'Técnico'), ('MESA_ENTRADA', 'Mesa de Entrada')], max_length=15, verbose_name='Emisor'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En Proceso'), ('ESCALADO', 'Escalado a Técnico'), ('ESCALADO_ADMIN', 'Escalado a Mesa de Entrada'), ('RESUELTO_BOT', 'Resuelto por Bot'), ('RESUELTO_TECNICO', 'Resuelto por Técnico'), ('CERRADO', 'Cerrado')], default='NUEVO', max_length=20, verbose_name='Estado del Ticket'),
        ),
    ]
