# Generated by Django 5.2.4 on 2025-08-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_knowledgedocument_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='tags',
            field=models.TextField(blank=True, help_text='Palabras clave o entidades relevantes extraídas del documento, ej: Infoges, VPN, Contraseña', null=True, verbose_name='Tags (separados por comas)'),
        ),
    ]
