# Generated by Django 5.2.4 on 2025-08-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_knowledgedocument_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='categoria',
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='subtema',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtema o Entidad Principal (ej. Infoges, VPN)'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='tema',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Abuso del sistema', 'Abuso del sistema'), ('General', 'General')], default='General', max_length=50, verbose_name='Tema Principal'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='tags',
            field=models.TextField(blank=True, help_text='Palabras clave relevantes, ej: acceso, contraseña, instalación', null=True, verbose_name='Tags (separados por comas)'),
        ),
    ]
